arch: 
  - ppc64le
  - amd64
  
dist: bionic

service: docker
sudo: required

script:
  - docker pull ibmcom/powerai:1.7.0-pytorch-ubuntu18.04-py37
  - docker run -a stdin -a stdout -a stderr -u root -v .:/home/conda/:rw,z ibmcom/powerai:1.7.0-pytorch-ubuntu18.04-py37 bash /home/conda/script.sh
