arch: 
  - ppc64le
  - amd64
  
dist: bionic

service: docker
sudo: required

script:
  - docker pull ibmcom/powerai:1.7.0-pytorch-ubuntu18.04-py37
  - sudo chmod +x script.sh
  - docker run -td --rm --name powerai ibmcom/powerai:1.7.0-pytorch-ubuntu18.04-py37 ./script
